### ISSUE TITLE
Custom configuration not working

### ISSUE THREAD

**Issue by mateusz-as** [mathieutu/babel-plugin-tailwind-rn-classname#3]
Hi I created fresh RN 0.64.2 app.
created tailwindRN.ts like in readme and muted it in root, generated styles.json in root and added configuration to babel.config.js like in readme.

i got:
App.js: ENOENT: no such file or directory, open './tailwindRN'

without tailwindRNExportPath and tailwindRNExportName in babel.config.js its working fine

**Comment by mathieutu** [comment]
Hi, could you please push your app somewhere so I can figure out what's not working?
Thanks.

**Comment by mateusz-as** [comment]
Hi: i pushed it here:
https://github.com/mateusz-as/tw_babel_test

**Comment by mathieutu** [comment]
ok thanks. 

Could you try with `"tailwindRNExportPath": "./tailwindRN.ts"` instead of `./tailwindRN`?

**Comment by mateusz-as** [comment]
Yes, that was a problem. It's working fine with extension. Thanks, great tool!

**Comment by mathieutu** [comment]
Great!
Thanks for having taken the time to test and report the issue, I'll update the documentation.
