### ISSUE TITLE
Generate custom tailwind styles and cannot using in className

### ISSUE THREAD

**Issue by uarefans** [mathieutu/babel-plugin-tailwind-rn-classname#5]
This package really helpful, thank you. I need some suggestion for what happen here. 

I'm using 
`$ npx tailwindcss init`
`$ npx create-tailwind-rn`
to generate custom tailwind

and works fine if using this
```
import { tw } from './tailwind';
<Text style={tw('bg-primary')}>aaaaa</Text>
```

but if using this, i get nothing
```
<Text className="bg-primary">aaaaa</Text>
```

This is my setup
```
**tailwind.js**
import { create } from 'tailwind-rn';
import styles from './styles.json';

const { tailwind, getColor } = create(styles);
export const tw = tailwind;
```

```
**jsconfig.json**
{
  "compilerOptions": {
    "baseUrl": "./src",
    "checkJs": true,
    "jsx": "react",
    "types": [
      "babel-plugin-tailwind-rn-classname"
    ]
  }
}
```

```
**babel.config.js**
module.exports = function(api) {
	api.cache(true);
	return {
		presets: [ 'babel-preset-expo' ],
		plugins: [
			'tailwind-rn-classname',
			{
				tailwindRNExportPath: './tailwind.js',
				tailwindRNExportName: 'tw'
			}
		]
	};
};
```

Any possible to using custom style from tailwind.config.js directly to className ? 

Thank you

**Comment by mathieutu** [comment]
Hi,
Yes it's possible, and it should work the way you did. Could you please provide a reproduction repo, so I can test your issue?

Thanks.

**Comment by uarefans** [comment]
Thank you for quick reply, repo is here https://github.com/uarefans/test-tailwind-rn

**Comment by uarefans** [comment]
Sorry, this issue solved, error / not showing style because cache and wrong plugin for babel name resolver. Thank you
